services:
  jupyter:
    build: .
    container_name: pyspark_jupyter
    ports:
      - "8888:8888"
    volumes:
      - .:/workspace
    working_dir: /workspace
    environment:
      - PYTHONPATH=/workspace/src

  streamlit:
      build: .
      container_name: pyspark_streamlit
      ports:
        - "8501:8501"
      volumes:
        - .:/workspace
      working_dir: /workspace
      environment:
        - PYTHONPATH=/workspace/src
      command: streamlit run app/streamlit_app.py --server.address=0.0.0.0 --server.port=8501